import type { FC } from 'react';
import type { TablerIconsProps } from '@tabler/icons-react';

export type TablerIcon = FC<TablerIconsProps>;

export {
    IconAlertCircle,
    IconArrowLeft,
    IconBook,
    IconBrandGithub,
    IconBrandMedium,
    IconBrandLinkedin,
    IconBrandWhatsapp,
    IconBrandYoutube,
    IconCheck,
    IconSelector,
    IconChevronDown,
    IconChevronRight,
    IconChevronUp,
    IconCircle,
    IconCopy,
    IconDeviceDesktop,
    IconDots,
    IconDownload,
    IconEye,
    IconEyeOff,
    IconFolder,
    IconFolderCode,
    IconLayoutGrid,
    IconLayoutSidebarLeftCollapse,
    IconLayoutSidebarLeftExpand,
    IconLoader2,
    IconLock,
    IconLogout,
    IconMail,
    IconMenu2,
    IconMinus,
    IconMoon,
    IconRefresh,
    IconScan,
    IconSearch,
    IconSettings,
    IconShieldCheck,
    IconSun,
    IconX,
} from '@tabler/icons-react';
